name: Test Lucee admin Upgrade

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: lucee-script-runner-maven-cache
      - name: Cache Lucee files
        uses: actions/cache@v3
        with:
          path: |
            _actions/lucee/script-runner/main/lucee-download-cache
            ./*.run
            ./*.lco
          key: lucee-downloads
      - name: install 5.4.2.17
        run: |
          curl https://cdn.lucee.org/lucee-5.4.2.17-linux-x64-installer.run -o lucee-linux-x64-installer.run
          ls -l
          chmod +x lucee-linux-x64-installer.run
          sudo ./lucee-linux-x64-installer.run \
            --mode unattended --prefix /tmp/lucee --installconn false --installmodcfml false --installiis false --startatboot false \
            --luceepass webweb --systemuser $USER --installjre true
          sleep 5;
          echo "<cfscript>if (server.lucee.version neq url.version) header statuscode='500' statustext='wrong version #server.lucee.version#'; echo('## Lucee Linux ' & server.lucee.version & ', using java ' & server.java.version);</cfscript>" > /tmp/lucee/tomcat/webapps/ROOT/check.cfm
          curl http://127.0.0.1:8888/index.cfm?version=5.4.2.17 --fail-with-body -o $GITHUB_STEP_SUMMARY
          #sleep 5
          #sudo /tmp/lucee/lucee_ctl stop
      - name: debug failure
        if: ${{ failure() }}
        run: |
            cat /tmp/lucee/tomcat/logs/catalina.out
            #cat /tmp/lucee/install.log
            cd /tmp/lucee
            ls -lR
            #cat /tmp/lucee/tomcat/lucee-server/context/logs/out.log
            #cat /tmp/lucee/tomcat/lucee-server/context/logs/err.log
            #cat /tmp/lucee/tomcat/logs/catalina.out
      - name: Checkout Lucee
        uses: actions/checkout@v3
        with:
          repository: lucee/lucee
          path: lucee
      - name: Run Lucee Test Suite, testFilter="adminPages" 5.4.2.17
        uses: lucee/script-runner@main
        with:
          webroot: ${{ github.workspace }}/lucee/test
          execute: /bootstrap-tests.cfm
          luceeVersion: light-5.4.3.2
        env:
          testFilter: remoteAdminPages
          testAdditional: ${{ github.workspace }}/tests
      - name: Upgrade Lucee to 5.4.3.2 via lco
        run: |
            curl https://cdn.lucee.org/5.4.3.5.lco -o 5.4.3.2.lco
            cp 5.4.3.2.lco /tmp/lucee/tomcat/lucee-server/deploy/5.4.3.2.lco
            echo "sleeping for 70s"
            sleep 70
            curl http://127.0.0.1:8888/index.cfm?version=5.4.3.2 --fail-with-body -o $GITHUB_STEP_SUMMARY
            ls -lR
      - name: Run Lucee Test Suite, testFilter="adminPages" 5.4.3.2
        uses: lucee/script-runner@main
        with:
          webroot: ${{ github.workspace }}/lucee/test
          execute: /bootstrap-tests.cfm
          luceeVersion: light-5.4.3.2
        env:
          testFilter: remoteAdminPages
          testAdditional: ${{ github.workspace }}/tests

