name: Test Lucee admin Upgrade

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: lucee-script-runner-maven-cache
      - name: Cache Lucee files
        uses: actions/cache@v3
        with:
          path: |
            _actions/lucee/script-runner/main/lucee-download-cache
            ./*.run
            ./*.lco
          key: lucee-downloads
      - name: install 5.4.2.17
        env:
          LUCEE_ADDITIONAL_CONFIG_SERVER_DIR: ${{ github.workspace }}
        run: |
          curl --fail https://cdn.lucee.org/lucee-5.4.2.17-linux-x64-installer.run -o lucee-linux-x64-installer.run
          ls -l
          mkdir -p /tmp/lucee/tomcat/lucee-server/context
          mkdir -p /tmp/lucee/tomcat/webapps/ROOT/WEB-INF/lucee
          cp .CFConfig.json /tmp/lucee/tomcat/lucee-server/context/.CFConfig.json
          cp lucee-server.xml /tmp/lucee/tomcat/lucee-server/context/lucee-server.xml
          cp .CFConfig.json /tmp/lucee/tomcat/webapps/ROOT/WEB-INF/lucee/.CFConfig.json
          chmod +x lucee-linux-x64-installer.run
          sudo ./lucee-linux-x64-installer.run \
            --mode unattended --prefix /tmp/lucee --installconn false --installmodcfml false --installiis false --startatboot false \
            --luceepass webweb --systemuser $USER --installjre true
          sleep 5;
          ls -l /tmp/lucee/tomcat/lucee-server/context
          echo "<cfscript>if (server.lucee.version neq url.version) header statuscode='500' statustext='wrong version #server.lucee.version#'; echo('## Lucee Linux ' & server.lucee.version & ', using java ' & server.java.version);</cfscript>" > /tmp/lucee/tomcat/webapps/ROOT/check.cfm
          curl http://127.0.0.1:8888/check.cfm?version=5.4.2.17 --fail-with-body -o $GITHUB_STEP_SUMMARY
          #sleep 5
          #sudo /tmp/lucee/lucee_ctl stop
          ls -lRHa /tmp/lucee/
          #cat /tmp/lucee/install.log
      - name: debug failure
        if: ${{ failure() }}
        run: |
            cat /tmp/lucee/tomcat/logs/catalina.out
            #cat /tmp/lucee/install.log
            cd /tmp/lucee
            ls -laRH
            #cat /tmp/lucee/tomcat/lucee-server/context/logs/out.log
            #cat /tmp/lucee/tomcat/lucee-server/context/logs/err.log
            #cat /tmp/lucee/tomcat/logs/catalina.out
      - name: Checkout Lucee
        uses: actions/checkout@v3
        with:
          repository: lucee/lucee
          path: lucee
      - name: Run Lucee Test Suite, testFilter="adminPages" 5.4.2.17
        uses: lucee/script-runner@main
        with:
          webroot: ${{ github.workspace }}/lucee/test
          execute: /bootstrap-tests.cfm
          luceeVersionQuery: 6/all/light
        env:
          testFilter: remoteAdminPages
          testAdditional: ${{ github.workspace }}/tests
      - name: Upgrade Lucee to 5.4.3.5-SNAPSHOT via lco
        run: |
            curl --fail https://cdn.lucee.org/5.4.3.5-SNAPSHOT.lco -o 5.4.3.5-SNAPSHOT.lco
            cp 5.4.3.5-SNAPSHOT.lco /tmp/lucee/tomcat/lucee-server/deploy/5.4.3.5-SNAPSHOT.lco
            ls -lR /tmp/lucee/tomcat/lucee-server/deploy
            echo "sleeping for 70s"
            sleep 70
            ls -lR /tmp/lucee/tomcat/lucee-server/deploy
            curl http://127.0.0.1:8888/check.cfm?version=5.4.3.5-SNAPSHOT --fail-with-body -o $GITHUB_STEP_SUMMARY
      - name: debug upgrade failure
        if: ${{ failure() }}
        run: |
            ls -lRa /tmp/lucee/tomcat/lucee-server/deploy
            ls -lR /tmp/lucee/tomcat/lucee-server/patches
            ls -lR /tmp/lucee/tomcat/lucee-server/context/logs
            ls -lR /tmp/lucee/tomcat/logs/
            cat /tmp/lucee/tomcat/lucee-server/context/logs/out.log
            cat /tmp/lucee/tomcat/lucee-server/context/logs/err.log
            cat /tmp/lucee/tomcat/lucee-server/context/logs/deploy.log
            cat /tmp/lucee/tomcat/logs/catalina.out
      - name: Run Lucee Test Suite, testFilter="adminPages" 5.4.3.5-SNAPSHOT
        uses: lucee/script-runner@main
        with:
          webroot: ${{ github.workspace }}/lucee/test
          execute: /bootstrap-tests.cfm
          luceeVersionQuery: 6/all/light
        env:
          testFilter: remoteAdminPages
          testAdditional: ${{ github.workspace }}/tests
      - name: debug failure - application.log TRACE
        if: ${{ failure() }}
        run: |
            echo "Server application.log"
            cat /tmp/lucee/tomcat/lucee-server/context/logs/application.log
            echo "Server out.log
            cat /tmp/lucee/tomcat/lucee-server/context/logs/out.log
            echo "Web application.log
            cat /tmp/lucee/tomcat/webapps/ROOT/WEB-INF/lucee/logs/application.log
            ls -lR /tmp/lucee/tomcat/webapps/ROOT/WEB-INF/lucee/

